### PR TITLE
Convert compass directions to screen directions

### PR DESCRIPTION
**Pull request by hawstom**
Change compass directions to up, down, left, right. I don't like this, but it's what was requested.

### CODE REVIEW

**Comment by Zamiell** [comment]
thank you!

> I don't like this

i acknowledge that we could go either way with this.
but I feel like assuming that north actually maps to "up" on a 2d game like this probably doesn't make sense, since it is possible that the camera is simply pointing in the opposite direction that you think it is, and there are no in-game references to north, south, east, or west, correct me if i am wrong

**Comment by hawstom** [comment]
I will be paying attention and let you know. :-D
--
Tom Haws 480-201-5476 (or NPS 480-389-4583)
"Forgiveness is the highest and most beautiful form of love. In return, you
will receive untold peace and happiness." -Dr. Robert Muller

**Comment by hawstom** [comment]
Here's what I recalled or found:

Intro: 
"... my pride and joy: ____ Farm. It's located in Stardew Valley, on the southern coast."

Living off the Land:
"This one's for you folks living in Stardew Valley. Check for Spring Onion southwest of town, where the river meets the ocean. You can sometimes find a whole bunch growing right out of the dirt."

Ginger Island (conceivably special):
"When dark clouds cry, begin your quest
To seek the fabled gem-birds four
Each day, one north, south, east, or west
Arrange their gifts upon my door"

Misc. Golden Walnut hints speak similarly of the island.

**Comment by Zamiell** [comment]
ok, i reverse my position

**Comment by Zamiell** [comment]
using north/south/east/west is fine, if you would like to change it back, you can, its up to you
(or if you want to use those words in future pull requests)

**Comment by hawstom** [comment]
OK. Maybe a "style guide" might be:
"The guide uses compass directions except in some cases when talking about
tool use." ?
--
Tom Haws 480-201-5476 (or NPS 480-389-4583)
"Forgiveness is the highest and most beautiful form of love. In return, you
will receive untold peace and happiness." -Dr. Robert Muller

**Comment by Zamiell** [comment]
seems fine with me!

**Pull request merged**
