### PR TITLE
Update Min-Max_Guide.md

### PR DESCRIPTION
**Pull request by hawstom**
Extensive discussed edits to Win Friends route.
Some edits to "save money for Fiberglass Rod".

### CODE REVIEW

**Comment by hawstom** [comment]
I already submitted this, but there was a typo.

Extensive discussed edits to Win Friends route.
Some edits to "save money for Fiberglass Rod".

**Comment by Zamiell** [comment]
can you revert your last commit, because it blew away my previous two commits

**Comment by hawstom** [comment]
For this guide, I have been using the Github.com interface instead of the command line, and I am fumbling around a bit. I am not sure how to revert, but I will hunt around.

**Comment by Zamiell** [comment]
ok, no problem, i will revert it

**Comment by hawstom** [comment]
Thanks. Sorry for the poor workflow.

**Comment by Zamiell** [comment]
are you a programmer? have u used git before?

**Comment by Zamiell** [comment]
also go ahead and re-do your edits now, make sure you are on latest commit first though

**Comment by hawstom** [comment]
Yeah. I love git. But I use it from the command line. And I haven't been doing that for this. 

I installed github desktop, and I am going to try to get used to it. I found how to revert with that gui. It seems more full-featured than the browser interface.

**Comment by hawstom** [comment]
Also, thinking about branches is a bit different with this than with software, so I have been a bit ham-handed. Sorry about that.

**Comment by Zamiell** [comment]
ugh, don't use github desktop, it is terrible

just use command line, if you are on windows, git comes with Git Bash, which is what I always use

**Comment by Zamiell** [comment]
although usually i make PR edits from the website, since it is handy for that

**Comment by hawstom** [comment]
Well, maybe that's what I will do. Pull requests are new to me. I haven't been on very big teams. So I have to get used to those. This is good for me.

**Comment by Zamiell** [comment]
yeah, pull requests are good to get used to.
i maintain some open source software so i am real used to getting PRs and the general workflow, now that i understand everything i like it a lot

**Comment by hawstom** [comment]
1. Do you use the gh cli? Or just normal git and manage the pull requests in the browser?
2. Would I clone directly from your account to my local, or would I clone, push, and pull to my github account and issue pull requests from that repo?

**Comment by Zamiell** [comment]
> Do you use the gh cli?

yes, its very nice for two reasons:
1) you don't have to type `git clone`, you can just copy-paste from the website the entire gh command and paste it in
2) you can type `gh checkout pr 123` if you need to mess with someone's PR

**Comment by Zamiell** [comment]
> Would I clone directly from your account to my local, or would I clone, push, and pull to my github account and issue pull requests from that repo?

um no, if you are working on a PR then you would clone your fork
like right now your pr is coming from here: https://github.com/hawstom/stardew-valley/tree/win-friends-route-per-discussion

**Comment by Zamiell** [comment]
it looks like you still haven't redone the edits from the revert, can you do that now?

**Comment by Zamiell** [comment]
i.e. there havn't been any commits since `Revert "Create Min-Max_Guide.md"`

**Comment by hawstom** [comment]
See what you think of this. It has your suggestions and your recent edits. I really like this and I am eager to test it.

**Comment by Zamiell** [comment]
you should not have any field snacks because you are saving all of your acorns, right?

**Comment by Zamiell** [comment]
i changed the wording to just always sell spring foragables, and worry about the CC quest later on

also, i dont think you should ever sell spring onions, since they are 0.62/0.56 GPE, and the extra wood is useful later on for the additional chests

**Comment by hawstom** [comment]
Field Snacks: I think I lost something in my edits. The previous version said (I don't know why it make the point) not to ship Field Snacks that may have come from a Garbage Can. That seems like quite a corner case to me. Make it however you want. I was just poorly trying to preserve the old content.

Spring Onions: If you are desperate for money, you are desperate. And they are no more worthless than Fiber. I think it boils down to an accounting decision for tomorrow's critical path toward a Fiberglass Rod. It's not something I think the guide can dictate.

**Comment by Zamiell** [comment]
> Field Snacks: I think I lost something in my edits. The previous version said (I don't know why it make the point) not to ship Field Snacks that may have come from a Garbage Can. That seems like quite a corner case to me. Make it however you want. I was just poorly trying to preserve the old content.

i see, yeah i agree that it is a corner case, lets delete it for now

**Comment by Zamiell** [comment]
> Spring Onions: If you are desperate for money, you are desperate. And they are no more worthless than Fiber. I think it boils down to an accounting decision for tomorrow's critical path toward a Fiberglass Rod. It's not something I think the guide can dictate.

i could be wrong but it seems unlikely that selling spring onions would make the difference between being able to buy the lv 2 before willy closes and not being able to.

are you sure?

**Comment by hawstom** [comment]
I'm thinking hard about this, and I am not sure. I am thinking hard about the critical path on Spring 2.

 - For good fishers, the critical path is easy: Buy Fiberglass Rod as early as possible, buy as much bait as possible before Fish Shop closes, and keep leveling up.

 - For mediocre fishers (like me), it gets harder because failure to get the Fiberglass Rod is a real threat: Is failure more likely due to insufficient skill/time or insufficient money. I think:
  - If you think failure is a real threat or you are having trouble succeeding at all, you need to get every single gp you can on Spring 1 once you have 50 Wood for your Spring 2 chest.
  - You may even consider minimizing your watering time by planting Mixed Seeds first, destroying Potatoes and all but 2 Cauli, and then planting only enough Parsnips to make 13.
  - If your skill is poor (fewer Perfect catches), you need all the time you can to reach Fishing level 2. So if you have over 1200 (this number needs to be tested and refined) after giving a Stone to Willy, don't leave the pier! Just start fishing.

Not sure. What do you think?

**Comment by Zamiell** [comment]
i think that if you just do a few runs where you practice day 2 a few times, you will get real good at fishing mini-game and this will become a non-issue =p

**Comment by hawstom** [comment]
Hahaha. I know it's tempting to think that. But I have been playing Stardew Valley a long time, I love fishing, and I never get any better. I have been playing the piano for decades, and I am no good. Some of us are simply not as dexterous as others. And if I get better, all that does is make me useless to write from the mediocre fisher's perspective. :-D

I can tell you this (as a competent mediocre) Stardew fisher:

- I have never yet made fishing level 4 on Spring 2.
- I always am down to the wire (last hour or so) on making fishing level 2 in time to buy a Fiberglass Rod.
- Having 400 bait when this guide says "500-700" is a good accomplishment for me.

I am not frustrated in the least by Stardew Valley fishing. I am happy with my skills. They are adequate for who I am and what I have. But those are my stats, and they aren't unusually bad.

**Comment by Zamiell** [comment]
keep in mind the time at which you buy the lv2 rod is mostly contingent in how much money you make from foragables on day 1, as opposed to how "good" you are at the fishing minigame.
i've had plenty of runs where i never switch back to the bamboo rod at all, and just do all training rod.
maybe the guide should be edited to say to never switch back to bamboo rod if you suck at fishing.
(in this context, perfect catches would only matter from X AM to 9 AM)

**Comment by hawstom** [comment]
It's also contingent on reaching fishing level 2, which takes some combination of hours and player skill. And hours also can be contingent on how much money you make on day 1 (if you are able to fish instead of going to the museum or even the beach). So money on day 1 is paramount, especially if player skill is not super high.

Maybe there are super poor fishers who wouldn't want to switch back to the bamboo pole because they can't catch anything with it. I can catch all the pertinent fish fine with the Bamboo Pole. I am in that fuzzy gray competent area between hopeless and stellar. And the forum discussions seemed to indicate that this is a big fuzzy area. There was no clear consensus about the Training Rod. Does it or does it not increase XP rate for a given mediocre player?

**Comment by hawstom** [comment]
Here's that reference I keep mentioning:
https://forums.stardewvalley.net/threads/level-up-fishing-fast-vs-the-training-rod

**Comment by Zamiell** [comment]
> Does it or does it not increase XP rate for a given mediocre player?

well yes, it does, right?
lets take this step by step

1) how fishing works is that you get a certain amount of XP per fish caught, and you get a 2.4x multiplier if you get a "Perfect" catch.
2) every player, regardless of skill, will be able to catch every fish that is hooked.
3) the only difference that skill makes is whether or not you get a perfect catch.
4) whether or not you get a perfect catch is a combination of your current fishing level (which determines the bar size) and player skill.
5) the point of the training rod is that it sets the player's fishing skill equal to level 5, which gives you a huge bar.
6) with the training rod, every player will be able to perfect catch every fish, regardless of skill level, because having a level 5 fishing bar is huge.
7) the general idea is that moving from the bamboo pole to the training rod at level 0 is a good idea, because it will be near-impossible to perfect catch every fish.
8) at fishing level 2, it's ambiguous as to whether moving from the bamboo pole to the training rod at level 0 is a good idea or not, because it's unclear as to whether you can still perfect catch every fish with a level 2 fishing bar.
9) at fishing level 4, it's probably a bad idea to move from the bamboo pole to the training rod, because the difference between the level 4 bar and the level 5 bar is very tiny.
10) it's objectively a bad idea to move from the bamboo pole to the training rod at level 5 and beyond, since it provides no benefit.

my main point is that even in the situation where you switch from the Bamboo Pole to the Training Rod as soon as humanly possible, and then you never switch back, you should **still** be able to purchase the level 2 rod before willy closes without a problem.
thus, i don't see player skill as affecting this process very much.

**Comment by hawstom** [comment]
1. Yes.
2. I don't follow. The only fish for which this is true is the first catch. We may **assume** that the audience of the guide can catch most every fish, and we can say so explicitly, that "This guide is for players who are able to catch every fish that is hooked on Spring 2." (Of course that cuts me out, but that's okay.)
3. Again, this is only true if you make it true by defining the audience. I recall losing one fish (for whatever excuse, I lost it) on my last trial yesterday. That said, speaking only for myself, yes, I catch nearly all fish on Spring 2 whichever rod I am using.
4. Yes.
5. Yes.
6. I don't follow again. This is only true if you define it to be true. In the real world it is not true. Speaking only for myself, no, I do not get even nearly every fish perfect.
7. Yes.
8. Yes. But I have an idea about that below.
9. Yes. I have made this point repeatedly in other places.
10. Yes. Obviously.
11. I guess you would need to watch me fish. :-D Yes. Player skill makes plenty of difference, because 100% perfect catches with the Training Rod is not mediocre fishing.

My suggestion is this:

If you reach fishing level 2 with hours to spare (2 or 3 p.m.? You tell me what time it is when you generally reach it), switch to the Bamboo Pole to maximize your income until the Fish Shop closes. (I don't know this is optimal, but it could be.)

Speaking for myself, I usually reach fishing level 2 with very little time to spare. So I wouldn't really have time to switch to the Bamboo Pole. And I need to rely on 1200 gp at the start of fishing to help me afford the Fiberglass Rod.

**Comment by Zamiell** [comment]
> The only fish for which this is true is the first catch.

what's different about the first catch?

**Comment by Zamiell** [comment]
> You tell me what time it is when you generally reach it

it's super variable, there's no "normal" time.
it mostly depends on whether or not you got like a bunch of foraging shipped + whether or not you got bubbles.

**Comment by Zamiell** [comment]
> Again, this is only true if you make it true by defining the audience. I recall losing one fish (for whatever excuse, I lost it) on my last trial yesterday. That said, speaking only for myself, yes, I catch nearly all fish on Spring 2 whichever rod I am using.

losing 1 fish over the course of the whole day isn't super significant.
so it sounds like we agree that nearly everyone who reads the guide will be able to catch almost every fish, with some small exceptions for only the worst fishers, and these exceptions aren't super significant.

**Comment by Zamiell** [comment]
> I don't follow again. This is only true if you define it to be true. In the real world it is not true. Speaking only for myself, no, I do not get even nearly every fish perfect.

what percentage of perfect do you get with training rod?

**Comment by Zamiell** [comment]
> I guess you would need to watch me fish. :-D

i feel like we might be getting confused and/or talking past each other.
allow me try to break this down further.
from your own admission, you
1) only lost 1 hooked fish over the course of the entire day, and
2) did not get 100% perfect catches with the training rod, getting X% perfect catches instead.

lets examine each of these in turn.

1 is relevant to gold income + experience gain.
with respect to the question of "will you be able to buy lv 2 rod before willy closes", we don't care all all about experience gain.
we only care about the gold loss.
the gold loss from exactly one fish is something around 60g, right?
the only time that this would matter if you were short exactly 60g for the rod when willy closed at 5pm, or something along those lines (which seems extremely unlikely).

2 is relevant only to experience gain, since perfect catches with the training rod don't affect quality.
with respect to the question of "will you be able to buy lv 2 rod before willy closes", we don't care all all about experience gain.
so 2 is a non-factor here.

thus, my initial claim that player skill does not play a significant factor in whether or not you will be able to buy the lv 2 rod before willy closes seems to be correct.

**Comment by hawstom** [comment]
I will do some calculations using your spreadsheet. Maybe that will be helpful. Stay tuned.

**Comment by hawstom** [comment]
Here are my calculations: https://docs.google.com/spreadsheets/d/1Hd7M6ITTDcdGbqGiTtgrp0vgXuJqLaCP2xJ3LaV8gbU/edit#gid=55943689

Bottom line is you seem to need something equivalent to 100% catches and 50% perfect catches if you have 7 hours to fish. Of course money is an entire other concern. If you don't have perfects to spare, you probably need to forego treasures until you get to level 2. Is that good thinking?

**Comment by Zamiell** [comment]
> This video I made explains and demonstrates.

oh, i see, i didnt know that you couldn't fail the first catch

**Comment by Zamiell** [comment]
> assuming that fish luck isn't a huge variable

my base assumption is that it is not a huge variable

**Comment by Zamiell** [comment]
> I can start fishing with 1300+ gp on hand and have the 1800gp before I reach level 2. It's close

oh, that's interesting.
yeah i guess that would make sense if you miss enough perfect catches

**Comment by Zamiell** [comment]
i am constantly clicking really fast when i fish, are you doing that?

**Pull request merged**
